#!/usr/bin/env bash
# Resolves the AWS account ID and GitHub organisation, then writes backend.hcl
# and terraform.tfvars files for each Terraform root module. Run once after
# infra/bootstrap has been applied, and again whenever a new developer clones
# the repository.
#
# Usage:
#   make infra-generate-backend-configs
#   AWS_PROFILE=<profile> scripts/generate-backend-configs.sh
#
# The generated files are gitignored — they are per-machine artifacts, not
# committed source. *.example files in each directory show the expected format.
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVS_DIR="${REPO_ROOT}/infra/environments"

AWS_PROFILE="${AWS_PROFILE:-example-monorepo-staging}"
REGION="${TF_REGION:-us-east-1}"
LOCK_TABLE="example-monorepo-terraform-locks"

# ── Resolve AWS account ────────────────────────────────────────────────────────

echo "→ Resolving AWS account ID (profile: ${AWS_PROFILE})"
ACCOUNT_ID=$(AWS_PROFILE="${AWS_PROFILE}" aws sts get-caller-identity --query Account --output text)

BUCKET="example-monorepo-tfstate-${ACCOUNT_ID}"

# ── Resolve GitHub organisation ───────────────────────────────────────────────
#
# Derived from the git remote URL so no manual input is required.
# Supports both SSH (git@github.com:org/repo.git) and HTTPS remotes.
# Override by setting GITHUB_ORG in the environment before running the script.

if [[ -z "${GITHUB_ORG:-}" ]]; then
  REMOTE_URL=$(git -C "${REPO_ROOT}" remote get-url origin 2>/dev/null || true)
  if [[ -n "${REMOTE_URL}" ]]; then
    # Strip protocol/host prefix, take the first path segment (the org).
    GITHUB_ORG=$(echo "${REMOTE_URL}" | sed 's|.*[:/]\([^/]*\)/[^/]*$|\1|')
  fi
fi

if [[ -z "${GITHUB_ORG:-}" ]]; then
  echo "✗ Could not derive GitHub organisation from git remote." >&2
  echo "  Set GITHUB_ORG=<org> and re-run the script." >&2
  exit 1
fi

echo "→ GitHub organisation: ${GITHUB_ORG}"

# ── Helpers ────────────────────────────────────────────────────────────────────

generate_backend_config() {
  local dir="$1"
  local key="$2"
  mkdir -p "${dir}"
  cat > "${dir}/backend.hcl" <<EOF
bucket         = "${BUCKET}"
key            = "${key}"
region         = "${REGION}"
dynamodb_table = "${LOCK_TABLE}"
encrypt        = true
EOF
  echo "→ Wrote ${dir}/backend.hcl"
}

generate_tfvars() {
  local dir="$1"
  mkdir -p "${dir}"
  cat > "${dir}/terraform.tfvars" <<EOF
# Generated by scripts/generate-backend-configs.sh — do not edit or commit.
github_org = "${GITHUB_ORG}"
EOF
  echo "→ Wrote ${dir}/terraform.tfvars"
}

# ── Bootstrap backend config ───────────────────────────────────────────────────
#
# Bootstrap uses a generated backend.tf (gitignored) rather than backend.hcl.
# When this file exists Terraform uses the S3 backend; when absent it uses
# local state. Delete the file to revert to local (e.g. for teardown).

BOOTSTRAP_DIR="${REPO_ROOT}/infra/bootstrap"
cat > "${BOOTSTRAP_DIR}/backend.tf" <<EOF
# Generated by scripts/generate-backend-configs.sh — do not edit or commit.
# Delete this file to revert bootstrap to local state (e.g. for teardown).
terraform {
  backend "s3" {
    bucket         = "${BUCKET}"
    key            = "bootstrap/terraform.tfstate"
    region         = "${REGION}"
    dynamodb_table = "${LOCK_TABLE}"
    encrypt        = true
  }
}
EOF
echo "→ Wrote ${BOOTSTRAP_DIR}/backend.tf"

# ── Discover and generate ──────────────────────────────────────────────────────

count=0

for env_dir in "${ENVS_DIR}"/*/; do
  environment="$(basename "${env_dir}")"
  apps_dir="${env_dir}apps"
  [[ -d "${apps_dir}" ]] || continue

  for app_dir in "${apps_dir}"/*/; do
    [[ -d "${app_dir}" ]] || continue
    # Skip placeholder directories that contain no Terraform files.
    compgen -G "${app_dir}*.tf" > /dev/null 2>&1 || continue

    app="$(basename "${app_dir}")"
    key="environments/${environment}/apps/${app}/terraform.tfstate"
    generate_backend_config "${app_dir%/}" "${key}"
    generate_tfvars "${app_dir%/}"
    (( count++ ))
  done
done

# ── Summary ────────────────────────────────────────────────────────────────────

echo "✓ Generated configs for account ${ACCOUNT_ID}, org ${GITHUB_ORG} (bootstrap + ${count} app module(s))."
echo "  Bootstrap: run 'make infra-bootstrap-migrate-state' if migrating for the first time,"
echo "             or 'make infra-bootstrap-init-remote' on an already-migrated account."
if (( count > 0 )); then
  echo "  Apps:      run 'make infra-init APP=<app> ENV=<env>' to initialise each module."
fi
